#pragma once

#define TDS_MSG_KEY_PRESSED 0
#define TDS_MSG_KEY_RELEASED 1
#define TDS_MSG_MOUSE_PRESSED 2
#define TDS_MSG_MOUSE_RELEASED 3
#define TDS_MSG_EDIT_TARGET 4
#define TDS_MSG_MAP_READY 5
#define TDS_MSG_DIALOG_START 6
#define TDS_MSG_DIALOG_STOP 7
