#pragma once

/*
 * Big file to include everything in TDS.
 */

#include "camera.h"
#include "clock.h"
#include "collision.h"
#include "config.h"
#include "display.h"
#include "effect.h"
#include "engine.h"
#include "handle.h"
#include "input.h"
#include "input_map.h"
#include "key_map.h"
#include "key_names.h"
#include "linmath.h"
#include "log.h"
#include "memory.h"
#include "msg.h"
#include "object.h"
#include "object_type_cache.h"
#include "render.h"
#include "savestate.h"
#include "script.h"
#include "signal.h"
#include "sound_buffer.h"
#include "sound_cache.h"
#include "sound_manager.h"
#include "sound_source.h"
#include "sprite_cache.h"
#include "sprite.h"
#include "tds.h"
#include "texture_cache.h"
#include "texture.h"
#include "util.h"
#include "vertex_buffer.h"
#include "vertex.h"
